language: python
python:
    - "3.6"
before_install:
    - pip install pytest
    - pip install pytest-cov
    - pip install coveralls
script:
   - pytest --cov=plsql_util
   - coverage report --fail-under=80
after_success:
  - coveralls
