language: python
python:
    - "3.6"
before_install:
    - pip install pytest
    - pip install pytest-cov
    - pip install coveralls
script:
   - pytest --cov=python_util_for_plsql/
after_success:
  - coveralls
