language: python
python:
- '3.6'
before_install:
- pip install -U pip
- python setup.py install
- pip install pytest
- pip install pytest-cov
- pip install coveralls
script:
- pytest --cov=python_util_for_plsql
- coverage report --fail-under=80
after_success:
- coveralls
deploy:
  provider: pypi
  user: walshdanny700
  password:
    secure: l721AEu+pxHDmIwPkxHzVPjJgiI4TxGRu7Gl9nRGu/OdYMRL+siVaooGMF92bgypRhSFKP9yHlM1SyNhqYHrk0bZA7QVCiv4ChvNB1w5Wl00bQaid3yVNuV7swJzYxNGmjzhYE7jHpIMJgYRxY6nBKb9W5JRdTQy2uE2bXlty9be+s7Gz2h0/DmiUUBea+72XrlIXacVnQkFabXDpp8r6mUTMoqB6QKoXOayIWdQxZdz/QZ2QAMLQXAaNR5UlOPan7n9eC/s1d6PD+tYRrBJUbvFjv1Fbuhp3T3IxGAlbQzgOL12Is1vCaqOv2fTiZMy5VwIGBGgb/anl+ScK4uqssbaacFvAluY23y5dxlvda4Cyq0XC4XDIB9VfFtxjxKQp+s+1bE1qwo2b8MpLLz/pyLfHsYjVWYdBtkgmwfoWHL3EBqLOJXATyC8JKF3C7OYsIjyeDK5hantTvnytHAA99BXUssm8cHMef/fxBAQ7j2KVvwdnbyqHX7bn3+TiU4W7RKX21E9X3RQvYhMsHovwKbAqHuRCA2YvsG88RmHs9n0X6K8L8tsEsDFR053G6r9sxkqnvkaMI137ykGzKEFNNk11zniue3zomJBPNJGMIsjY6emcNYkabRzKnrZGcSMeBotVHpw9pp5nriEBhOnzk6sVqlST9XY/SpwwLjSOJA=
true:
  tags: true
